name = "jdk25"
name_cn = "Java Development Kit 25"
description = "Eclipse Temurin OpenJDK 25"
author = "cyanteam"
contact = "qtof@qq.com"
version = "0.0.0"
language = "java"
architecture = "multi"
package_id = "lang.java.jdk25"

[config_command]
common = "{install_path}/_CYPASSETS/bin/java"
macosarm64 = "{install_path}/_CYPASSETS/bin/java"
macosintel = "{install_path}/_CYPASSETS/bin/java"
linux64 = "{install_path}/_CYPASSETS/bin/java"
linuxarm64 = "{install_path}/_CYPASSETS/bin/java"
win64 = "{install_path}/_CYPASSETS/bin/java.exe"

[bin_commands]
jar = "{install_path}/_CYPASSETS/bin/jar"
jarsigner = "{install_path}/_CYPASSETS/bin/jarsigner"
java = "{install_path}/_CYPASSETS/bin/java"
javac = "{install_path}/_CYPASSETS/bin/javac"
javadoc = "{install_path}/_CYPASSETS/bin/javadoc"
javap = "{install_path}/_CYPASSETS/bin/javap"
jcmd = "{install_path}/_CYPASSETS/bin/jcmd"
jconsole = "{install_path}/_CYPASSETS/bin/jconsole"
jdb = "{install_path}/_CYPASSETS/bin/jdb"
jdeprscan = "{install_path}/_CYPASSETS/bin/jdeprscan"
jdeps = "{install_path}/_CYPASSETS/bin/jdeps"
jfr = "{install_path}/_CYPASSETS/bin/jfr"
jimage = "{install_path}/_CYPASSETS/bin/jimage"
jinfo = "{install_path}/_CYPASSETS/bin/jinfo"
jlink = "{install_path}/_CYPASSETS/bin/jlink"
jmap = "{install_path}/_CYPASSETS/bin/jmap"
jmod = "{install_path}/_CYPASSETS/bin/jmod"
jps = "{install_path}/_CYPASSETS/bin/jps"
jshell = "{install_path}/_CYPASSETS/bin/jshell"
jstack = "{install_path}/_CYPASSETS/bin/jstack"
jstat = "{install_path}/_CYPASSETS/bin/jstat"
keytool = "{install_path}/_CYPASSETS/bin/keytool"

[assets]
